In [5]:
import torch
n = torch.load('./models/cifar10_4x_03171441_acc74.pth')
print(list(n.parameters()))

[Parameter containing:
tensor([[[[ 2.0949e-01,  2.1283e-01, -4.3062e-01, -1.4861e-01, -2.5372e-01],
          [ 3.3572e-01,  3.5189e-02, -3.6674e-01, -3.5928e-01, -1.4631e-01],
          [ 3.5913e-01,  2.4480e-01, -2.2228e-01, -6.2798e-01, -7.2961e-02],
          [ 3.5576e-01,  2.6992e-01, -2.7795e-01,  1.2586e-02, -2.7735e-02],
          [ 1.9943e-01,  2.1116e-01, -2.4603e-05, -3.8295e-02, -2.7630e-01]],

         [[-4.6654e-01, -3.2759e-02,  3.5020e-02,  3.5259e-01,  3.6759e-03],
          [-3.5421e-01,  9.2278e-02,  3.1595e-01,  3.6396e-02,  4.9554e-02],
          [ 3.2545e-02,  9.0750e-02, -2.2179e-01, -4.8481e-01, -4.6877e-01],
          [ 1.7701e-01,  1.9789e-01, -1.8826e-01, -4.5572e-01, -9.0748e-02],
          [ 1.2451e-01,  6.4498e-02,  2.2101e-01,  5.8765e-03,  1.3954e-01]],

         [[ 2.5817e-02,  1.3852e-01, -1.0005e-01, -3.4464e-02, -1.7662e-01],
          [ 4.1879e-01,  3.0935e-01,  4.6640e-02, -2.1425e-01, -1.4988e-01],
          [-2.2031e-01, -1.0302e-01, -3.6637e-01,

In [8]:
list(n.manyResBlock[0].parameters())

[Parameter containing:
 tensor([[[[ 2.0949e-01,  2.1283e-01, -4.3062e-01, -1.4861e-01, -2.5372e-01],
           [ 3.3572e-01,  3.5189e-02, -3.6674e-01, -3.5928e-01, -1.4631e-01],
           [ 3.5913e-01,  2.4480e-01, -2.2228e-01, -6.2798e-01, -7.2961e-02],
           [ 3.5576e-01,  2.6992e-01, -2.7795e-01,  1.2586e-02, -2.7735e-02],
           [ 1.9943e-01,  2.1116e-01, -2.4603e-05, -3.8295e-02, -2.7630e-01]],
 
          [[-4.6654e-01, -3.2759e-02,  3.5020e-02,  3.5259e-01,  3.6759e-03],
           [-3.5421e-01,  9.2278e-02,  3.1595e-01,  3.6396e-02,  4.9554e-02],
           [ 3.2545e-02,  9.0750e-02, -2.2179e-01, -4.8481e-01, -4.6877e-01],
           [ 1.7701e-01,  1.9789e-01, -1.8826e-01, -4.5572e-01, -9.0748e-02],
           [ 1.2451e-01,  6.4498e-02,  2.2101e-01,  5.8765e-03,  1.3954e-01]],
 
          [[ 2.5817e-02,  1.3852e-01, -1.0005e-01, -3.4464e-02, -1.7662e-01],
           [ 4.1879e-01,  3.0935e-01,  4.6640e-02, -2.1425e-01, -1.4988e-01],
           [-2.2031e-01, -1.0302e-0

In [9]:
list(n.manyResBlock[1].parameters())

[Parameter containing:
 tensor([[[[ 2.0949e-01,  2.1283e-01, -4.3062e-01, -1.4861e-01, -2.5372e-01],
           [ 3.3572e-01,  3.5189e-02, -3.6674e-01, -3.5928e-01, -1.4631e-01],
           [ 3.5913e-01,  2.4480e-01, -2.2228e-01, -6.2798e-01, -7.2961e-02],
           [ 3.5576e-01,  2.6992e-01, -2.7795e-01,  1.2586e-02, -2.7735e-02],
           [ 1.9943e-01,  2.1116e-01, -2.4603e-05, -3.8295e-02, -2.7630e-01]],
 
          [[-4.6654e-01, -3.2759e-02,  3.5020e-02,  3.5259e-01,  3.6759e-03],
           [-3.5421e-01,  9.2278e-02,  3.1595e-01,  3.6396e-02,  4.9554e-02],
           [ 3.2545e-02,  9.0750e-02, -2.2179e-01, -4.8481e-01, -4.6877e-01],
           [ 1.7701e-01,  1.9789e-01, -1.8826e-01, -4.5572e-01, -9.0748e-02],
           [ 1.2451e-01,  6.4498e-02,  2.2101e-01,  5.8765e-03,  1.3954e-01]],
 
          [[ 2.5817e-02,  1.3852e-01, -1.0005e-01, -3.4464e-02, -1.7662e-01],
           [ 4.1879e-01,  3.0935e-01,  4.6640e-02, -2.1425e-01, -1.4988e-01],
           [-2.2031e-01, -1.0302e-0